# Generated by Django 5.1.3 on 2024-11-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_book_author_en_book_author_ru_book_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='author'),
        ),
        migrations.AddField(
            model_name='book',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='book',
            name='sub_title_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='sub_title'),
        ),
        migrations.AddField(
            model_name='book',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=100, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author_en',
            field=models.CharField(max_length=100, null=True, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(blank=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AlterField(
            model_name='book',
            name='sub_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='sub_title'),
        ),
        migrations.AlterField(
            model_name='book',
            name='sub_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='sub_title'),
        ),
        migrations.AlterField(
            model_name='book',
            name='sub_title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='sub_title'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
    ]
